import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { NextPage } from 'next';

const Hello: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          Hello
          <br />
          <button
            onClick={async () => {
              await fetch('/pokemon/ditto', {
                method: 'get',
              });
            }}
          >
            Hello Pokemon
          </button>
          <br />
          <button
            onClick={async () => {
              await fetch('/api/hello', {
                method: 'get',
              });
            }}
          >
            Hello serverless
          </button>
        </div>
      </main>
    </>
  );
};

export default Hello;
